name: Build and Publish Wheels

on:
  push:
    branches:
      - main
      - "2026"
      - "2025"
      - apiwheel-update-main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build

      - name: Build wheels
        run: |
          python -m build --wheel --outdir dist/ .

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels
          path: dist/*.whl
